### **Parte 3 - Red Neuronal Recurrente**

**Base de datos de comentarios de películas**: El objetivo será analizar y predecir la reseña de películas mediante análisis de sentimiento.

In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical
import re

**Carga de dataset**

In [2]:
data = pd.read_csv("/content/drive/My Drive/Universidad Galileo/Tercer Trimestre/Statistical Learning II/Proyecto/3-RNN/data.csv")

In [43]:
data.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [4]:
print(data.sentiment)

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 50000, dtype: object


**Normalización y Tokenización**

In [5]:
data['review'] = data['review'].apply(lambda x: x.lower())
data['review'] = data['review'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))

for idx,row in data.iterrows():
    row[0] = row[0].replace('rt',' ')

max_fatures = 2000
tokenizer = Tokenizer(num_words=max_fatures, split=' ')
tokenizer.fit_on_texts(data['review'].values)
X = tokenizer.texts_to_sequences(data['review'].values)
X = pad_sequences(X)

**Definición de la arquitectura**

In [ ]:
embed_dim = 128
lstm_out = 196

model = Sequential()
model.add(Embedding(max_fatures, embed_dim,input_length = X.shape[1]))
model.add(SpatialDropout1D(0.4))
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(2,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])

**Cantidad de parametros generados**

In [6]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1880, 128)         256000    
_________________________________________________________________
spatial_dropout1d (SpatialDr (None, 1880, 128)         0         
_________________________________________________________________
lstm (LSTM)                  (None, 196)               254800    
_________________________________________________________________
dense (Dense)                (None, 2)                 394       
Total params: 511,194
Trainable params: 511,194
Non-trainable params: 0
_________________________________________________________________
None


**One-hot encoding de la categoría del sentimiento (positivo, negativo)**

In [ ]:
Y = pd.get_dummies(data['sentiment']).values

**Set de entrenamiento y pruebas**

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.33, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(33500, 1880) (33500, 2)
(16500, 1880) (16500, 2)


**Entrenamiento**

In [8]:
batch_size = 256
model.fit(X_train, Y_train, epochs = 5, steps_per_epoch=50, batch_size=batch_size, verbose = 1)

Epoch 1/5
50/50 [==============================] - 1946s 39s/step - loss: 0.6567 - accuracy: 0.6359
Epoch 2/5
50/50 [==============================] - 1939s 39s/step - loss: 0.4283 - accuracy: 0.8067
Epoch 3/5
50/50 [==============================] - 1966s 39s/step - loss: 0.3604 - accuracy: 0.8479
Epoch 4/5
50/50 [==============================] - 2011s 40s/step - loss: 0.3270 - accuracy: 0.8656
Epoch 5/5
50/50 [==============================] - 1983s 40s/step - loss: 0.3113 - accuracy: 0.8735


In [10]:
validation_size = 1500

X_validate = X_test[-validation_size:]
Y_validate = Y_test[-validation_size:]
X_test = X_test[:-validation_size]
Y_test = Y_test[:-validation_size]
score,acc = model.evaluate(X_test, Y_test, verbose = 1, batch_size = batch_size)
print("score: %.2f" % (score))
print("acc: %.2f" % (acc))

53/53 [==============================] - 391s 7s/step - loss: 0.2933 - accuracy: 0.8777
score: 0.29
acc: 0.88


In [ ]:
pos_cnt, neg_cnt, pos_correct, neg_correct = 0, 0, 0, 0
for x in range(len(X_validate)):
    
    result = model.predict(X_validate[x].reshape(1,X_test.shape[1]),batch_size=1,verbose = 2)[0]
   
    if np.argmax(result) == np.argmax(Y_validate[x]):
        if np.argmax(Y_validate[x]) == 0:
            neg_correct += 1
        else:
            pos_correct += 1
       
    if np.argmax(Y_validate[x]) == 0:
        neg_cnt += 1
    else:
        pos_cnt += 1

In [13]:
print("pos_acc", pos_correct/pos_cnt*100, "%")
print("neg_acc", neg_correct/neg_cnt*100, "%")

pos_acc 90.52496798975672 %
neg_acc 81.91933240611962 %


**Experimentos**

In [21]:

def get_sentiment(review):
  review = tokenizer.texts_to_sequences(review)
  review = pad_sequences(review, maxlen=1880, dtype='int32', value=0)
  print(review)
  sentiment = model.predict(review,batch_size=1,verbose = 1)[0]
  if(np.argmax(sentiment) == 0):
      print("negative")
  elif (np.argmax(sentiment) == 1):
      print("positive")


In [44]:
get_sentiment("Probably my alltime favorite movie")

[[   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0 1563]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    9]
 [   0    0    0 ...    0    0    0]]
34/34 [==============================] - 16s 474ms/step
positive


In [34]:
get_sentiment("This a fantastic movie of three prisoners who become famous one of the actors is george clooney")

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 154]
 [  0   0   0 ...   0   0   9]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 378]]
95/95 [==============================] - 45s 477ms/step
positive
